// <copyright file="Namespace.cs" company="Gamma Four, Inc.">
//    Copyright © 2018 - Gamma Four, Inc.  All Rights Reserved.
// </copyright>
// <author>Donald Roy Airey</author>
namespace GammaFour.DataModelGenerator.Server
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using GammaFour.DataModelGenerator.Common;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.CSharp;
    using Microsoft.CodeAnalysis.CSharp.Syntax;

    /// <summary>
    /// The root namespace.
    /// </summary>
    public class Namespace
    {
        /// <summary>
        /// The data model schema.
        /// </summary>
        private DataModelSchema dataModelSchema;

        /// <summary>
        /// Initializes a new instance of the <see cref="Namespace"/> class.
        /// </summary>
        /// <param name="dataModelSchema">The name of the namespace.</param>
        public Namespace(DataModelSchema dataModelSchema)
        {
            // Initialize the object.
            this.dataModelSchema = dataModelSchema;

            // This is the syntax of the namespace.
            this.Syntax = SyntaxFactory.NamespaceDeclaration(
                    SyntaxFactory.IdentifierName(dataModelSchema.TargetNamespace))
                .WithUsings(SyntaxFactory.List<UsingDirectiveSyntax>(this.UsingStatements))
                .WithMembers(this.Members)
                .WithLeadingTrivia(this.LeadingTrivia)
                .WithTrailingTrivia(this.TrailingTrivia);
        }

        /// <summary>
        /// Gets or sets gets the syntax.
        /// </summary>
        public NamespaceDeclarationSyntax Syntax
        {
            get;
            set;
        }

        /// <summary>
        /// Gets the documentation comment.
        /// </summary>
        private SyntaxTriviaList LeadingTrivia
        {
            get
            {
                // The document comment trivia is collected in this list.
                List<SyntaxTrivia> trivia = new List<SyntaxTrivia>();

                // // <auto-generated />
                trivia.Add(
                    SyntaxFactory.Comment("// <auto-generated />"));

                // #pragma warning disable SA1402
                trivia.Add(
                    SyntaxFactory.Trivia(
                        SyntaxFactory.PragmaWarningDirectiveTrivia(
                            SyntaxFactory.Token(SyntaxKind.DisableKeyword),
                            true)
                        .WithErrorCodes(
                            SyntaxFactory.SingletonSeparatedList<ExpressionSyntax>(
                                SyntaxFactory.IdentifierName("SA1402")))));

                // #pragma warning disable SA1649
                trivia.Add(
                    SyntaxFactory.Trivia(
                        SyntaxFactory.PragmaWarningDirectiveTrivia(
                            SyntaxFactory.Token(SyntaxKind.DisableKeyword),
                            true)
                        .WithErrorCodes(
                            SyntaxFactory.SingletonSeparatedList<ExpressionSyntax>(
                                SyntaxFactory.IdentifierName("SA1649")))));

                // This is the complete document comment.
                return SyntaxFactory.TriviaList(trivia).NormalizeWhitespace();
            }
        }

        /// <summary>
        /// Gets the members.
        /// </summary>
        private SyntaxList<MemberDeclarationSyntax> Members
        {
            get
            {
                // Create the members.
                SyntaxList<MemberDeclarationSyntax> members = default(SyntaxList<MemberDeclarationSyntax>);
                members = this.CreatePublicInterfaces(members);
                members = this.CreatePublicClasses(members);
                return members;
            }
        }

        /// <summary>
        /// Gets the trailing trivia.
        /// </summary>
        private SyntaxTriviaList TrailingTrivia
        {
            get
            {
                // The document comment trivia is collected in this list.
                List<SyntaxTrivia> trivia = new List<SyntaxTrivia>();

                // #pragma warning restore SA1402
                trivia.Add(
                    SyntaxFactory.Trivia(
                        SyntaxFactory.PragmaWarningDirectiveTrivia(
                            SyntaxFactory.Token(SyntaxKind.DisableKeyword),
                            true)
                        .WithErrorCodes(
                            SyntaxFactory.SingletonSeparatedList<ExpressionSyntax>(
                                SyntaxFactory.IdentifierName("SA1402")))));

                // #pragma warning restore SA1649
                trivia.Add(
                    SyntaxFactory.Trivia(
                        SyntaxFactory.PragmaWarningDirectiveTrivia(
                            SyntaxFactory.Token(SyntaxKind.DisableKeyword),
                            true)
                        .WithErrorCodes(
                            SyntaxFactory.SingletonSeparatedList<ExpressionSyntax>(
                                SyntaxFactory.IdentifierName("SA1649")))));

                // This is the complete document comment.
                return SyntaxFactory.TriviaList(trivia).NormalizeWhitespace();
            }
        }

        /// <summary>
        /// Gets the 'using' statements.
        /// </summary>
        private List<UsingDirectiveSyntax> UsingStatements
        {
            get
            {
                // Create the 'using' statements.
                // [TODO] Make the addition of user namespaces part of the initialization.  Run through the tables and extract the
                // namespaces from the types found therein.
                List<UsingDirectiveSyntax> usingStatements = new List<UsingDirectiveSyntax>();
                usingStatements.Add(SyntaxFactory.UsingDirective(SyntaxFactory.IdentifierName("System")));
                usingStatements.Add(SyntaxFactory.UsingDirective(SyntaxFactory.IdentifierName("System.Collections.Generic")));
                usingStatements.Add(SyntaxFactory.UsingDirective(SyntaxFactory.IdentifierName("System.Collections.ObjectModel")));
                usingStatements.Add(SyntaxFactory.UsingDirective(SyntaxFactory.IdentifierName("System.Diagnostics")));
                usingStatements.Add(SyntaxFactory.UsingDirective(SyntaxFactory.IdentifierName("System.Diagnostics.CodeAnalysis")));
                usingStatements.Add(SyntaxFactory.UsingDirective(SyntaxFactory.IdentifierName("System.Linq")));
                usingStatements.Add(SyntaxFactory.UsingDirective(SyntaxFactory.IdentifierName("System.Threading")));
                usingStatements.Add(SyntaxFactory.UsingDirective(SyntaxFactory.IdentifierName("System.Transactions")));
                usingStatements.Add(SyntaxFactory.UsingDirective(SyntaxFactory.IdentifierName("GammaFour.ClientModel")));
                usingStatements.Add(SyntaxFactory.UsingDirective(SyntaxFactory.IdentifierName("GammaFour.ServiceModel")));
                return usingStatements;
            }
        }

        /// <summary>
        /// Creates the classes.
        /// </summary>
        /// <param name="members">The collection of members.</param>
        /// <returns>The collection of members augmented with the classes.</returns>
        private SyntaxList<MemberDeclarationSyntax> CreatePublicClasses(SyntaxList<MemberDeclarationSyntax> members)
        {
            // Create the data for the row classes.
            List<Common.RowDataClass.Class> rowDataClasses = new List<Common.RowDataClass.Class>();
            foreach (TableSchema tableSchema in this.dataModelSchema.Tables)
            {
                rowDataClasses.Add(new Common.RowDataClass.Class(tableSchema));
            }

            // Alphabetize the list of row classes and add them to the structure.
            foreach (Common.RowDataClass.Class rowDataClass in rowDataClasses.OrderBy(c => c.Name))
            {
                members = members.Add(rowDataClass.Syntax);
            }

            // Create the row classes.
            List<RowClass.Class> rowClasses = new List<RowClass.Class>();
            foreach (TableSchema tableSchema in this.dataModelSchema.Tables)
            {
                rowClasses.Add(new RowClass.Class(tableSchema));
            }

            // Alphabetize the list of row classes and add them to the structure.
            foreach (RowClass.Class rowClass in rowClasses.OrderBy(c => c.Name))
            {
                members = members.Add(rowClass.Syntax);
            }

            // Create the list of row change event classes.
            List<Common.RowChangeEventArgsClass.Class> rowChangeEventClasses = new List<Common.RowChangeEventArgsClass.Class>();
            foreach (TableSchema tableSchema in this.dataModelSchema.Tables)
            {
                rowChangeEventClasses.Add(new Common.RowChangeEventArgsClass.Class(tableSchema));
            }

            // Alphabetize the list of change event classes and add them to the structure.
            foreach (Common.RowChangeEventArgsClass.Class @class in rowChangeEventClasses.OrderBy(c => c.Name))
            {
                members = members.Add(@class.Syntax);
            }

            // Create the list of tables.
            List<TableClass.Class> tableClasses = new List<TableClass.Class>();
            foreach (TableSchema tableSchema in this.dataModelSchema.Tables)
            {
                tableClasses.Add(new TableClass.Class(tableSchema));
            }

            // Alphabetize the list of tables and add them to the structure.
            foreach (TableClass.Class @class in tableClasses.OrderBy(c => c.Name))
            {
                members = members.Add(@class.Syntax);
            }

            // The actual data model class.
            members = members.Add(new DataModelClass.Class(this.dataModelSchema).Syntax);

            // Holds the individual transactions used to reconcile the client data models.
            members = members.Add(new TransactionLogItemClass.Class(this.dataModelSchema).Syntax);

            // Create the unique index classes.
            List<UniqueKeyIndexClass.Class> uniqueIndexClasses = new List<UniqueKeyIndexClass.Class>();
            foreach (TableSchema tableSchema in this.dataModelSchema.Tables)
            {
                foreach (ConstraintSchema constraintSchema in tableSchema.Constraints)
                {
                    UniqueConstraintSchema uniqueConstraintSchema = constraintSchema as UniqueConstraintSchema;
                    if (uniqueConstraintSchema != null)
                    {
                        uniqueIndexClasses.Add(new UniqueKeyIndexClass.Class(uniqueConstraintSchema));
                    }
                }
            }

            // Alphabetize the list of unique indices and add them to the structure.
            foreach (UniqueKeyIndexClass.Class @class in uniqueIndexClasses.OrderBy(c => c.Name))
            {
                members = members.Add(@class.Syntax);
            }

            // Create the list of foreign indices.
            List<ForeignKeyIndexClass.Class> foreignIndexClasses = new List<ForeignKeyIndexClass.Class>();
            foreach (RelationSchema relationSchema in this.dataModelSchema.Relations)
            {
                foreignIndexClasses.Add(new ForeignKeyIndexClass.Class(relationSchema));
            }

            // Alphabetize the list of foreign indices and add them to the structure.
            foreach (ForeignKeyIndexClass.Class @class in foreignIndexClasses.OrderBy(c => c.Name))
            {
                members = members.Add(@class.Syntax);
            }

            // This is the collection of alphabetized fields.
            return members;
        }

        /// <summary>
        /// Creates the classes.
        /// </summary>
        /// <param name="members">The collection of members.</param>
        /// <returns>The collection of members augmented with the classes.</returns>
        private SyntaxList<MemberDeclarationSyntax> CreatePublicInterfaces(SyntaxList<MemberDeclarationSyntax> members)
        {
            // The interface for implementing a persistent store.
            members = members.Add(new PersistentStoreageInterface.Interface(this.dataModelSchema).Syntax);

            // This is the collection of alphabetized fields.
            return members;
        }
    }
}